version: '3'

services:
    web:
        container_name:  djangoapp
        build: ./api/
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin1234

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

#    db:
#        image: postgres
#        environment:
#            - POSTGRES_DB=postgres
#            - POSTGRES_USER=postgres
#            - POSTGRES_PASSWORD=postgres